#' @include numerical_fallbacks.R
NULL


#' Legendre Polynomial Basis
#'
#' @description
#' The S7 class of Legendre polynomial bases, the objects [poly_basis()]
#' returns. It adds no property to [basis] and exists as the class the
#' Legendre methods dispatch on: every one of [basis_eval()],
#' [basis_deriv()], [basis_int()], [basis_gram()] and [basis_colnames()] has a
#' closed-form method registered here, so nothing about a Legendre basis is
#' computed by finite differences.
#'
#' @details
#' # Where the numbers come from
#'
#' The polynomials are generated by the three-term recurrence
#' \deqn{(n+1) P_{n+1}(t) = (2n+1)\, t\, P_n(t) - n\, P_{n-1}(t),}
#' on \eqn{t \in [-1, 1]}, with \eqn{P_0 = 1} and \eqn{P_1 = t}, and the
#' variable shifted from the basis interval by
#' \eqn{t = 2(x - \ell)/(u - \ell) - 1}.
#'
#' Derivatives come from the same recurrence differentiated,
#' \eqn{P_{n+1}^{(d)} = P_{n-1}^{(d)} + (2n+1) P_n^{(d-1)}}, so every order is
#' exact and no order is a special case; see [legendre_deriv()]. The integral
#' uses \eqn{\int P_n = (P_{n+1} - P_{n-1})/(2n+1)} and is exact as well.
#'
#' # Its `basis_params`
#'
#' One entry, `degree`, equal to `dimension - 1`, the highest degree the basis
#' carries. Nothing else is stored: the polynomials are determined by the
#' interval and the count.
#'
#' @inheritParams basis
#'
#' @return An object of class `PolyBasis`, inheriting from [basis], with the
#'   same five properties and `basis_params` holding `degree`. Call
#'   [poly_basis()] instead of this class directly; it validates its arguments
#'   and fills in `basis_name` and `basis_params`.
#'
#' @seealso [poly_basis()], the constructor;
#'   [basis_eval.PolyBasis()], [basis_deriv.PolyBasis()],
#'   [basis_int.PolyBasis()] and [basis_gram.PolyBasis()] for the methods
#'   registered on it.
#'
#' @examples
#' p <- poly_basis(dimension = 4)
#' S7::S7_inherits(p, PolyBasis)
#' p@basis_params$degree
#'
#' # No component of a Legendre basis is numerical.
#' basis_is_numerical(p)
#'
#' @export
PolyBasis <- S7::new_class("PolyBasis", parent = basis)


#' Construct a Legendre Polynomial Basis
#'
#' @description
#' Returns a basis of the polynomials of degree below `dimension` on
#' \eqn{[\ell, u]}, written in the Legendre polynomials and not in raw powers.
#' The two span the same space, so a fit through either gives the same curve;
#' the Legendre form is the one that survives being fitted, its Gram matrix
#' being diagonal where the raw powers' is a Hilbert matrix.
#'
#' @details
#' # Why not raw powers
#'
#' Fitting \eqn{1, x, x^2, \ldots} on \eqn{[0, 1]} gives the Gram matrix
#' \eqn{H_{mn} = 1/(m + n + 1)}, the Hilbert matrix, whose condition number
#' grows geometrically. The condition numbers of the two order-0 Gram
#' matrices, measured on \eqn{[0, 1]}:
#'
#' | `dimension` | Legendre | raw powers |
#' |---|---|---|
#' | 5 | 9 | 4.8e+05 |
#' | 10 | 19 | 1.6e+13 |
#' | 15 | 29 | 2.5e+17 |
#'
#' At ten raw powers a least-squares solve has already lost most of its
#' digits; at fifteen the matrix is numerically singular. The Legendre
#' condition number is \eqn{2K - 1}, growing linearly.
#'
#' # The Gram matrix
#'
#' The polynomials are orthogonal on their own interval,
#' \eqn{\int_{-1}^{1} P_m P_n \,\mathrm{d}t = 2\delta_{mn}/(2n+1)}, so
#' `basis_gram(p)` is diagonal with entries \eqn{(u - \ell)/(2n+1)} for
#' \eqn{n = 0, \ldots, K-1}. They are **not** orthonormal: pass the basis
#' through [orthonorm_basis()] for that.
#'
#' # Degree and dimension
#'
#' `dimension` counts functions and the degrees start at zero, so
#' `poly_basis(dimension = 4)` holds \eqn{P_0, P_1, P_2, P_3}, a cubic. The
#' basis contains the constant, so it is collinear with an intercept in the
#' same design; drop one or the other, or use [constrain_basis()].
#'
#' @param lower,upper The endpoints of the interval, each a single finite
#'   number with `lower < upper`. Default \eqn{[0, 1]}. Evaluating outside
#'   throws.
#' @param dimension The number of polynomials, a single whole number of at
#'   least 1, default `4`. The highest degree is `dimension - 1`, so `1` gives
#'   the constant alone.
#'
#' @return An object of class [PolyBasis], with `basis_name` `"legendre"`,
#'   `basis_params` holding `degree = dimension - 1`, and column names `P0`,
#'   `P1`, and so on.
#'
#' @references
#' Abramowitz, M. and Stegun, I. A. (1964). *Handbook of Mathematical
#' Functions*, chapter 22. National Bureau of Standards.
#'
#' @seealso [bspline_basis()] for a local basis and [fourier_basis()] for a
#'   periodic one; [orthonorm_basis()] to make the Gram matrix the identity;
#'   [basis_gram()] for the roughness penalty of this basis.
#'
#' @examples
#' p <- poly_basis(dimension = 5)
#' p
#'
#' # Orthogonal, so the Gram matrix is diagonal, with entries (u - l)/(2n + 1).
#' round(diag(basis_gram(p)), 8)
#' 1 / (2 * (0:4) + 1)
#'
#' # And well conditioned where the raw powers are not.
#' H <- outer(0:9, 0:9, function(a, b) 1 / (a + b + 1))
#' c(legendre = kappa(basis_gram(poly_basis(dimension = 10)), exact = TRUE),
#'   raw_powers = kappa(H, exact = TRUE))
#'
#' # It spans the same space as the raw powers, so a cubic is fitted exactly.
#' x <- seq(0, 1, length.out = 40)
#' max(abs(lm.fit(basis_eval(p, x), x^3)$fitted.values - x^3))
#'
#' # P_n(1) = 1 and P_n(-1) = (-1)^n, at the two ends of the interval.
#' basis_eval(p, c(0, 1))
#'
#' # Derivatives above the highest degree are exactly zero.
#' range(basis_deriv(p, c(0.2, 0.8), order = 5))
#'
#' @export
poly_basis <- function(lower = 0, upper = 1, dimension = 4) {
  dimension <- check_basis_args(lower, upper, dimension)
  PolyBasis(
    basis_name = "legendre",
    dimension = dimension,
    lower = lower,
    upper = upper,
    basis_params = list(degree = dimension - 1L)
  )
}


#' Column Names of a Legendre Basis
#'
#' @name basis_colnames.PolyBasis
#'
#' @description
#' Names the columns `P0`, `P1`, ..., `P(dimension - 1)`, so that a column's
#' name is the degree of the polynomial in it. This replaces the default
#' `le1`, `le2` of [basis_colnames.basis()], where the number would be the
#' degree plus one and a reader would have to remember the offset.
#'
#' @param basis A [PolyBasis] object.
#' @param ... Unused, and accepted so that the signature matches the generic's.
#'
#' @return A character vector of length `basis@dimension`, `"P0"` first.
#'
#' @seealso [basis_colnames()] for the generic.
#'
#' @keywords internal
S7::method(basis_colnames, PolyBasis) <- function(basis, ...) {
  paste0("P", seq_len(basis@dimension) - 1L)
}


#' Evaluate a Legendre Basis
#'
#' @name basis_eval.PolyBasis
#'
#' @description
#' Evaluates \eqn{P_0, \ldots, P_{K-1}} at the given points by the three-term
#' recurrence
#' \deqn{(n+1) P_{n+1}(t) = (2n+1)\, t\, P_n(t) - n\, P_{n-1}(t),}
#' after shifting the points from \eqn{[\ell, u]} onto \eqn{[-1, 1]} by
#' \eqn{t = 2(x - \ell)/(u - \ell) - 1}. The recurrence is stable on that
#' interval, every \eqn{|P_n| \le 1} there, so no rescaling is needed at any
#' dimension.
#'
#' @details
#' One pass builds the whole table, column \eqn{n+1} from columns \eqn{n} and
#' \eqn{n-1}, at a cost of \eqn{O(nK)} for `n` points. Missing points give
#' missing rows.
#'
#' The values at the ends are exact: \eqn{P_n(u) = 1} for every \eqn{n}, and
#' \eqn{P_n(\ell) = (-1)^n}.
#'
#' @param basis A [PolyBasis] object.
#' @param x A numeric vector of evaluation points inside the basis interval.
#' @param ... Unused, and accepted so that the signature matches the generic's.
#'
#' @return A numeric matrix with `length(x)` rows and `basis@dimension`
#'   columns, with column names `P0`, `P1`, and so on.
#'
#' @seealso [legendre_table()], which holds the recurrence;
#'   [basis_eval()] for the generic.
#'
#' @keywords internal
S7::method(basis_eval, PolyBasis) <- function(basis, x, ...) {
  name_columns(legendre_deriv(basis, x, 0L), basis)
}


#' Derivatives of a Legendre Basis
#'
#' @name basis_deriv.PolyBasis
#'
#' @description
#' Returns the `order`-th derivative of every Legendre polynomial, exactly and
#' at any order, from the recurrence
#' \eqn{P_{n+1}^{(d)} = P_{n-1}^{(d)} + (2n+1) P_n^{(d-1)}}. No difference is
#' taken anywhere, so the fourth derivative is as accurate as the first, and
#' an order above `basis@basis_params$degree` returns exact zeros.
#'
#' @details
#' Each order is built from the one below it, so reaching order \eqn{d} costs
#' \eqn{d} passes over a table of \eqn{K} columns. The shift onto
#' \eqn{[-1, 1]} contributes a factor \eqn{(2/(u - \ell))^d} by the chain
#' rule, applied once at the end.
#'
#' @param basis A [PolyBasis] object.
#' @param x A numeric vector of evaluation points inside the basis interval.
#' @param order The derivative order, a single non-negative whole number,
#'   default `1`. Above `dimension - 1` the result is exactly zero.
#' @param ... Unused, and accepted so that the signature matches the generic's.
#'
#' @return A numeric matrix with `length(x)` rows and `basis@dimension`
#'   columns, with column names `P0`, `P1`, and so on.
#'
#' @seealso [legendre_deriv()], which holds the recurrence;
#'   [basis_deriv()] for the generic.
#'
#' @keywords internal
S7::method(basis_deriv, PolyBasis) <- function(basis, x, order = 1L, ...) {
  name_columns(legendre_deriv(basis, x, order), basis)
}


#' Integral of a Legendre Basis
#'
#' @name basis_int.PolyBasis
#'
#' @description
#' Returns \eqn{\int_{\ell}^{x} P_n(t)\,\mathrm{d}t} for every polynomial,
#' in closed form and with no quadrature. The zero at the lower endpoint that
#' [basis_int()] promises falls out of the identity used and needs no
#' correction term.
#'
#' @details
#' The identity is \eqn{\int P_n = (P_{n+1} - P_{n-1})/(2n+1)} for
#' \eqn{n \ge 1}, with \eqn{\int P_0 = t}, so one table of \eqn{K + 1}
#' polynomials supplies all \eqn{K} integrals: the integral of the last one
#' reaches one degree beyond the basis.
#'
#' The anchoring is automatic. At \eqn{t = -1}, which is the lower endpoint,
#' \eqn{P_{n+1} - P_{n-1}} is \eqn{(-1)^{n+1} - (-1)^{n-1} = 0}, and the
#' \eqn{n = 0} column is written as \eqn{(t + 1)/2 \cdot (u - \ell)}, which
#' also vanishes there. Every column is therefore exactly zero at
#' `basis@lower`, with no cancellation of large numbers behind it.
#'
#' @param basis A [PolyBasis] object.
#' @param x A numeric vector of evaluation points inside the basis interval.
#' @param ... Unused, and accepted so that the signature matches the generic's.
#'
#' @return A numeric matrix with `length(x)` rows and `basis@dimension`
#'   columns, exactly zero in the row at `basis@lower`.
#'
#' @seealso [basis_int()] for the generic and the anchoring convention;
#'   [legendre_table()], which supplies the polynomials.
#'
#' @keywords internal
S7::method(basis_int, PolyBasis) <- function(basis, x, ...) {
  k <- basis@dimension
  half <- (basis@upper - basis@lower) / 2
  t <- (x - basis@lower) / half - 1

  # One degree beyond the basis, since the integral of P_n uses P_{n+1}.
  p <- legendre_table(t, k + 1L)
  out <- matrix(NA_real_, length(x), k)
  out[, 1L] <- (t + 1) * half
  if (k > 1L) {
    for (n in seq_len(k - 1L)) {
      out[, n + 1L] <- (p[, n + 2L] - p[, n]) / (2 * n + 1) * half
    }
  }
  out[is.na(x), ] <- NA_real_
  name_columns(out, basis)
}


#' Gram Matrix of a Legendre Basis
#'
#' @name basis_gram.PolyBasis
#'
#' @description
#' Returns the inner products of the `order`-th derivatives exactly, with no
#' quadrature error at any order. At `order = 0` the matrix is diagonal and
#' written down; above that a Gauss-Legendre rule with as many nodes as the
#' basis has functions integrates the product exactly, the integrand being a
#' polynomial of low enough degree.
#'
#' @details
#' # Order zero
#'
#' The polynomials satisfy
#' \eqn{\int_{-1}^{1} P_m P_n \,\mathrm{d}t = 2\delta_{mn}/(2n+1)}, so on
#' \eqn{[\ell, u]} the matrix is diagonal with entries
#' \eqn{(u - \ell)/(2n+1)}. It is written directly and costs nothing.
#'
#' # Higher orders
#'
#' Derivatives of Legendre polynomials are not orthogonal, so the matrix is
#' full. The integrand \eqn{P_m^{(d)} P_n^{(d)}} is a polynomial of degree at
#' most \eqn{2(K - 1 - d)}, and a \eqn{K}-node Gauss-Legendre rule is exact
#' to degree \eqn{2K - 1}, which is larger for every \eqn{d \ge 1}. The
#' quadrature is therefore exact to rounding, and the result is symmetrized as
#' `(G + t(G))/2` because the two triangles of a crossproduct differ in their
#' last bits.
#'
#' An `order` above `dimension - 1` returns the zero matrix, every derivative
#' having vanished.
#'
#' @param basis A [PolyBasis] object.
#' @param order The derivative order, a single non-negative whole number,
#'   default `0`.
#' @param at,weight Handled in the body of [basis_gram()] before dispatch, so
#'   they never arrive here. Named only because S7 requires a method's formals
#'   to contain the generic's.
#' @param ... Unused, and accepted so that the signature matches the generic's.
#'
#' @return A symmetric numeric matrix of `basis@dimension` rows and columns,
#'   with column names `P0`, `P1`, and so on. Diagonal at `order = 0`,
#'   singular with an `order`-dimensional null space above it, and exactly
#'   zero above `dimension - 1`.
#'
#' @seealso [basis_gram()] for the generic and the alternative measures.
#'
#' @keywords internal
S7::method(basis_gram, PolyBasis) <- function(basis, order = 0L, at = NULL,
                                              weight = NULL, ...) {
  k <- basis@dimension
  nm <- basis_colnames(basis)
  width <- basis@upper - basis@lower

  if (order == 0L) {
    d <- width / (2 * (seq_len(k) - 1L) + 1)
    return(matrix(diag(d, nrow = k), k, k, dimnames = list(nm, nm)))
  }
  if (order > basis@basis_params$degree) {
    return(matrix(0, k, k, dimnames = list(nm, nm)))
  }

  r <- quad_rule(c(basis@lower, basis@upper), n = k)
  b <- basis_deriv(basis, r$nodes, order = order)
  g <- crossprod(sqrt(r$weights) * b)
  g <- (g + t(g)) / 2
  dimnames(g) <- list(nm, nm)
  g
}


#' The Legendre Polynomials by Recurrence
#'
#' @description
#' Builds a table of \eqn{P_0, \ldots, P_{k-1}} evaluated at `t` on
#' \eqn{[-1, 1]}, one column per polynomial, from the three-term recurrence
#' \deqn{(n+1) P_{n+1}(t) = (2n+1)\, t\, P_n(t) - n\, P_{n-1}(t),}
#' seeded with \eqn{P_0 = 1} and \eqn{P_1 = t}. Used by
#' [basis_eval.PolyBasis()] and, at one extra column, by
#' [basis_int.PolyBasis()].
#'
#' @details
#' The recurrence is evaluated in the standard variable, never in the basis
#' interval's own, because \eqn{|P_n(t)| \le 1} on \eqn{[-1, 1]} and the
#' recurrence is stable there. Cost is \eqn{O(nk)} for `n` points, one column
#' per step.
#'
#' `t` is not range-checked here; the caller has already shifted validated
#' points onto \eqn{[-1, 1]}. Outside that interval the recurrence still runs
#' and the polynomials grow without bound.
#'
#' @param t A numeric vector on \eqn{[-1, 1]}, the evaluation points already
#'   shifted.
#' @param k The number of polynomials, a whole number of at least 1.
#'
#' @return A numeric matrix with `length(t)` rows and `k` columns, no
#'   dimnames. Column 1 is the constant 1.
#'
#' @seealso [legendre_deriv()], which starts from this table.
#'
#' @keywords internal
legendre_table <- function(t, k) {
  out <- matrix(0, length(t), k)
  out[, 1L] <- 1
  if (k > 1L) out[, 2L] <- t
  if (k > 2L) {
    for (n in seq_len(k - 2L)) {
      out[, n + 2L] <- ((2 * n + 1) * t * out[, n + 1L] - n * out[, n]) /
        (n + 1)
    }
  }
  out
}


#' Derivatives of the Legendre Polynomials
#'
#' @description
#' Computes the `order`-th derivative of \eqn{P_0, \ldots, P_{K-1}} with
#' respect to `x` on the basis interval. The one routine behind both
#' [basis_eval.PolyBasis()], which calls it at order 0, and
#' [basis_deriv.PolyBasis()].
#'
#' @details
#' Differentiating \eqn{P_{n+1}' - P_{n-1}' = (2n+1) P_n} repeatedly gives
#' \deqn{P_{n+1}^{(d)} = P_{n-1}^{(d)} + (2n+1)\, P_n^{(d-1)},}
#' which builds order \eqn{d} from order \eqn{d-1} in closed form, with no
#' difference taken anywhere. The seeds are \eqn{P_0^{(d)} = 0} for
#' \eqn{d \ge 1} and \eqn{P_1' = 1}, \eqn{P_1^{(d)} = 0} above.
#'
#' The loop runs `order` times over a `length(x)` by `K` table, so the cost is
#' \eqn{O(d n K)}, and it produces exact zeros once every polynomial has been
#' differentiated away. The shift onto \eqn{[-1, 1]} contributes
#' \eqn{(2/(u - \ell))^d}, applied once after the loop.
#'
#' @param basis A [PolyBasis] object.
#' @param x A numeric vector of evaluation points inside the basis interval.
#' @param order The derivative order, a single non-negative whole number.
#'   Order 0 returns the polynomials themselves.
#'
#' @return A numeric matrix with `length(x)` rows and `basis@dimension`
#'   columns, no dimnames, `NA` in the rows where `x` is `NA`.
#'
#' @seealso [legendre_table()], which supplies order 0.
#'
#' @keywords internal
legendre_deriv <- function(basis, x, order) {
  k <- basis@dimension
  half <- (basis@upper - basis@lower) / 2
  t <- (x - basis@lower) / half - 1

  cur <- legendre_table(t, k)
  if (order > 0L) {
    for (d in seq_len(order)) {
      nxt <- matrix(0, length(t), k)
      if (k > 1L) nxt[, 2L] <- if (d == 1L) 1 else 0
      if (k > 2L) {
        for (n in seq_len(k - 2L)) {
          nxt[, n + 2L] <- nxt[, n] + (2 * n + 1) * cur[, n + 1L]
        }
      }
      cur <- nxt
    }
    cur <- cur / half^order
  }
  cur[is.na(x), ] <- NA_real_
  cur
}
