#' @include numerical_fallbacks.R
NULL


#' Legendre Polynomial Basis
#'
#' @description
#' The S7 class of Legendre polynomial bases. Constructed by
#' \code{\link{poly_basis}}.
#'
#' @details
#' The polynomials are generated by the three-term recurrence
#' \deqn{(n+1) P_{n+1}(t) = (2n+1)\, t\, P_n(t) - n\, P_{n-1}(t),}
#' on \eqn{t \in [-1, 1]}, shifted to the basis interval. Derivatives come from
#' the derivative of the same recurrence, so every order is exact and no order
#' is special, and the integral from
#' \eqn{\int P_n = (P_{n+1} - P_{n-1})/(2n+1)} is exact as well.
#'
#' @inheritParams basis
#'
#' @return An object of class \code{PolyBasis}. Use \code{\link{poly_basis}}
#'   rather than calling the class directly.
#'
#' @seealso \code{\link{poly_basis}}
#'
#' @examples
#' p <- poly_basis(dimension = 4)
#' S7::S7_inherits(p, PolyBasis)
#'
#' @export
PolyBasis <- S7::new_class("PolyBasis", parent = basis)


#' Construct a Legendre Polynomial Basis
#'
#' @description
#' The polynomials of degree below \code{dimension} on \eqn{[\ell, u]},
#' expressed in the Legendre basis rather than in raw powers.
#'
#' @details
#' The Legendre polynomials span exactly the same space as
#' \eqn{1, x, x^2, \ldots}, and the choice between them is numerical. Raw
#' powers give a Gram matrix that is a Hilbert matrix, whose condition number
#' grows so fast that a basis of ten of them is already close to singular in
#' double precision. The Legendre polynomials are orthogonal, so their Gram
#' matrix is diagonal and perfectly conditioned.
#'
#' @param lower,upper The endpoints of the interval.
#' @param dimension The number of polynomials, so the highest degree is
#'   \code{dimension - 1}.
#'
#' @return An object of class \code{\link{PolyBasis}}.
#'
#' @seealso \code{\link{bspline_basis}}, \code{\link{fourier_basis}}
#'
#' @examples
#' p <- poly_basis(dimension = 5)
#' p
#'
#' # orthogonal, so the Gram matrix is diagonal
#' round(basis_gram(p), 10)
#'
#' # and it spans the same space as the raw powers
#' x <- seq(0, 1, length.out = 40)
#' fitted <- lm.fit(basis_eval(p, x), x^3)$fitted.values
#' max(abs(fitted - x^3))
#'
#' @export
poly_basis <- function(lower = 0, upper = 1, dimension = 4) {
  dimension <- check_basis_args(lower, upper, dimension)
  PolyBasis(
    basis_name = "legendre",
    dimension = dimension,
    lower = lower,
    upper = upper,
    basis_params = list(degree = dimension - 1L)
  )
}


#' Column Names of a Legendre Basis
#'
#' @name basis_colnames.PolyBasis
#' @description The polynomials numbered by their degree, from zero.
#' @param basis A \code{\link{PolyBasis}} object.
#' @param ... Unused.
#' @return A character vector of length \code{basis@dimension}.
#' @keywords internal
S7::method(basis_colnames, PolyBasis) <- function(basis, ...) {
  paste0("P", seq_len(basis@dimension) - 1L)
}


#' Evaluate a Legendre Basis
#'
#' @name basis_eval.PolyBasis
#' @description The three-term recurrence, on the shifted variable.
#' @param basis A \code{\link{PolyBasis}} object.
#' @param x A numeric vector of evaluation points.
#' @param ... Unused.
#' @return A numeric matrix with \code{length(x)} rows and
#'   \code{basis@dimension} columns.
#' @keywords internal
S7::method(basis_eval, PolyBasis) <- function(basis, x, ...) {
  name_columns(legendre_deriv(basis, x, 0L), basis)
}


#' Derivatives of a Legendre Basis
#'
#' @name basis_deriv.PolyBasis
#' @description
#' Exact derivatives of any order, from the derivative of the recurrence. An
#' order above the highest degree gives the zero matrix.
#' @param basis A \code{\link{PolyBasis}} object.
#' @param x A numeric vector of evaluation points.
#' @param order The derivative order.
#' @param ... Unused.
#' @return A numeric matrix with \code{length(x)} rows and
#'   \code{basis@dimension} columns.
#' @keywords internal
S7::method(basis_deriv, PolyBasis) <- function(basis, x, order = 1L, ...) {
  name_columns(legendre_deriv(basis, x, order), basis)
}


#' Integral of a Legendre Basis
#'
#' @name basis_int.PolyBasis
#' @description
#' The exact integral from the lower endpoint.
#' @details
#' From \eqn{\int P_n = (P_{n+1} - P_{n-1})/(2n+1)} for \eqn{n \ge 1} and
#' \eqn{\int P_0 = t}. The convention is satisfied without a correction: at
#' \eqn{t = -1} the combination \eqn{P_{n+1} - P_{n-1}} is
#' \eqn{(-1)^{n+1} - (-1)^{n-1} = 0}, and the constant term is anchored by
#' construction.
#' @param basis A \code{\link{PolyBasis}} object.
#' @param x A numeric vector of evaluation points.
#' @param ... Unused.
#' @return A numeric matrix with \code{length(x)} rows and
#'   \code{basis@dimension} columns.
#' @keywords internal
S7::method(basis_int, PolyBasis) <- function(basis, x, ...) {
  k <- basis@dimension
  half <- (basis@upper - basis@lower) / 2
  t <- (x - basis@lower) / half - 1

  # One degree beyond the basis, since the integral of P_n uses P_{n+1}.
  p <- legendre_table(t, k + 1L)
  out <- matrix(NA_real_, length(x), k)
  out[, 1L] <- (t + 1) * half
  if (k > 1L) {
    for (n in seq_len(k - 1L)) {
      out[, n + 1L] <- (p[, n + 2L] - p[, n]) / (2 * n + 1) * half
    }
  }
  out[is.na(x), ] <- NA_real_
  name_columns(out, basis)
}


#' Gram Matrix of a Legendre Basis
#'
#' @name basis_gram.PolyBasis
#' @description
#' Exact inner products: diagonal in closed form at order zero, and by an exact
#' Gauss-Legendre rule above it.
#' @details
#' The Legendre polynomials satisfy
#' \eqn{\int_{-1}^{1} P_m P_n \, \mathrm{d}t = 2\delta_{mn}/(2n+1)}, so on the
#' basis interval the order-zero matrix is diagonal with entries
#' \eqn{(u - \ell)/(2n+1)}. At higher orders the derivatives are no longer
#' orthogonal, but the integrand stays a polynomial of degree at most
#' \eqn{2(K - 1 - d)}, so a rule with \eqn{K} nodes integrates it exactly.
#' @param basis A \code{\link{PolyBasis}} object.
#' @param order The derivative order.
#' @param at,weight Handled by the generic before dispatch; unused here.
#' @param ... Unused.
#' @return A symmetric numeric matrix with \code{basis@dimension} rows and
#'   columns.
#' @keywords internal
S7::method(basis_gram, PolyBasis) <- function(basis, order = 0L, at = NULL,
                                              weight = NULL, ...) {
  k <- basis@dimension
  nm <- basis_colnames(basis)
  width <- basis@upper - basis@lower

  if (order == 0L) {
    d <- width / (2 * (seq_len(k) - 1L) + 1)
    return(matrix(diag(d, nrow = k), k, k, dimnames = list(nm, nm)))
  }
  if (order > basis@basis_params$degree) {
    return(matrix(0, k, k, dimnames = list(nm, nm)))
  }

  r <- quad_rule(c(basis@lower, basis@upper), n = k)
  b <- basis_deriv(basis, r$nodes, order = order)
  g <- crossprod(sqrt(r$weights) * b)
  g <- (g + t(g)) / 2
  dimnames(g) <- list(nm, nm)
  g
}


#' The Legendre Polynomials by Recurrence
#'
#' @description
#' A table of \eqn{P_0, \ldots, P_{k-1}} evaluated at \code{t} in
#' \eqn{[-1, 1]}, from the three-term recurrence.
#'
#' @param t A numeric vector in \eqn{[-1, 1]}.
#' @param k The number of polynomials.
#'
#' @return A numeric matrix with \code{length(t)} rows and \code{k} columns.
#'
#' @keywords internal
legendre_table <- function(t, k) {
  out <- matrix(0, length(t), k)
  out[, 1L] <- 1
  if (k > 1L) out[, 2L] <- t
  if (k > 2L) {
    for (n in seq_len(k - 2L)) {
      out[, n + 2L] <- ((2 * n + 1) * t * out[, n + 1L] - n * out[, n]) /
        (n + 1)
    }
  }
  out
}


#' Derivatives of the Legendre Polynomials
#'
#' @description
#' The \code{order}-th derivative of \eqn{P_0, \ldots, P_{K-1}} with respect to
#' \code{x}, on the basis interval.
#'
#' @details
#' Differentiating the identity
#' \eqn{P_{n+1}' - P_{n-1}' = (2n+1) P_n} repeatedly gives
#' \eqn{P_{n+1}^{(d)} = P_{n-1}^{(d)} + (2n+1) P_n^{(d-1)}}, which builds each
#' order from the one below it in closed form, with no differencing anywhere.
#' The chain rule for the shift to \eqn{[\ell, u]} contributes
#' \eqn{(2/(u-\ell))^{d}}.
#'
#' @param basis A \code{\link{PolyBasis}} object.
#' @param x A numeric vector of evaluation points.
#' @param order The derivative order.
#'
#' @return A numeric matrix with \code{length(x)} rows and
#'   \code{basis@dimension} columns.
#'
#' @keywords internal
legendre_deriv <- function(basis, x, order) {
  k <- basis@dimension
  half <- (basis@upper - basis@lower) / 2
  t <- (x - basis@lower) / half - 1

  cur <- legendre_table(t, k)
  if (order > 0L) {
    for (d in seq_len(order)) {
      nxt <- matrix(0, length(t), k)
      if (k > 1L) nxt[, 2L] <- if (d == 1L) 1 else 0
      if (k > 2L) {
        for (n in seq_len(k - 2L)) {
          nxt[, n + 2L] <- nxt[, n] + (2 * n + 1) * cur[, n + 1L]
        }
      }
      cur <- nxt
    }
    cur <- cur / half^order
  }
  cur[is.na(x), ] <- NA_real_
  cur
}
